notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email: github@tixz.dk
  api_key:
    secure: NjiRu61z/CLGaVpKrHcJFCthEMlY3WvU5omCLoQrAtw3U37XaafUYUIOHlB+mNzfW+RCC4K6BzZ4U4/zqndFLiu86AYSSSLdok0WYPORLJ1gLAbRc/oLBZ4H5WMVw7Z+dvPm7fQG21aEAK9Uutkvc3XdHuKsJARQFBNQnd+vWaZ37xcoyqQDzFHfrKwqHidy2NK8UK5HzfrEAzN4wYFt6ts5bsyFxb5rZqer3I+XiLE/N4oZRrcojNJXv1NxQ5OEnmbA6NqIPX8bu2BzZmw1n87dkP5aat3nyouAcd4FP62/PVP7UvmzhRyhhLsFk6qAGJThQxtnxHVEIT8gTa+Syjt/Jyz4vJXCmdT4d1WnXO1Gq+toAGZG2Ok7i9cuMqcv01OHfPY8AVnCWXHqoJZQPIXHhRAXaCfSFB0l9oTCcNdYGHx/WjFxfY9ypIgZXtX1ewXyjMR4cyn9BO2E5r8yzr9gL14UyjBm3Xdt0QuVmVqXPTDOruvGpX2yYHdJYBQKp63BgG3xFkZj5cvdKl/t0iFPIAl9qkhn6IUsLZOR8dC1oBXM9qqBbCzs0U1SjFuYk8rICVO3NraIAkRJYggDLfN2WUJMzQVGoCjCjey7p4su644BPuK6XZjNcCRF9RFPYAywd27daLDFWRoD7PSHbtuyNFoDEEofSTBgLwxd5LY=
  on:
    tags: true
