notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email: github@tixz.dk
  api_key:
    secure: IauBn9je9pJpVQDBSogBK7IHCNQa89dvRw33BDVb7hl55p/Lcb4N1bOKgga0QpkkbVuK82Rz3EqcUVvhxsIYAqEo5Orf0JqgzDTII2YGdMDd554Vv6zpjXd7HnrIBcEUIrm/U8dN5nxznmBzKtR7HzoFzp4JAQH0kgUUhrrm0fd+HEvMwpEnNjnc3JO999S4okIZhjiU9PupPhObDry7F7Uuw2SJ6ogj0Ff5TDd4XBMv5ZPFmVsym4gVYKRaF55iSuhV9uG8cm3DnsnQ90/MIOW2eI0vj5XQ/9lIIGb+x5WWWHZAyQgHJIbu7wd7rKlyJg3DtFBUpzcrbnoi0UkKHGy/GouYXkTgfnkDXdBoa6G3Ba9LXe5Opj/AXN/pgZb/9KmZt8B7m031+/gqqEFzbguGEDnsd5uTvsT7M4Z5TRPDbVJuQZArFz1qhp1ZTRQ0LBQxbs6GwrGf4MUDmA1CWY+IMEgYDmFKd1eLm+483cWzpv6/hIrMZCsUlwmQq58rZnzmHWcy6+60lNRlHFg1m2iVGZ03bn7GmVj2TAhawMnoao8ccc2iM8InEHze0U9HFVEpzWuMTcDJvNkyqQFvUyGiN3fDJncv2i516Fnqh/iyKkIyX6djcHfu4WhJmahwmn+jhwUIm++ZRd0lsaJNJCwUxlmiMqsmquNkZ/N5FRk=
  on:
    tags: true
